application: fresh-cherries
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon.ico

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
